### ISSUE TITLE
Update Registration Link

### ISSUE THREAD

**Issue by ram-nad** [Project-Club-IIITS/hacktoberfest-event-2019#5]
The **Register** Button links to the old form. It should link to the new registration form for event on 19th.

**Comment by b30wulffz** [comment]
I would like to work upon this issue. Please assign it to me.

**Comment by ram-nad** [comment]
Go ahead Shlok.

**Comment by masterashu** [comment]
Yeh kya hai?:confused:

**Comment by b30wulffz** [comment]
@masterashu 
We were testing something.
